export enum ActionType {
  FETCH_FIELDS = 'FETCH_FIELDS',
  FETCH_VALUES = 'FETCH_VALUES',
  FETCH_AREAS = 'FETCH_AREAS',
  SEND_VALUE = 'SEND_VALUE',
  CLEAR = 'CLEAR',
  TELE_UPDATE_TELEGRAM = 'TELE_UPDATE_TELEGRAM',
  TELE_RECORD_USERNAME = 'TELE_RECORD_USERNAME',
}
export enum MutationType {
  UPDATE_VALUE = 'UPDATE_VALUE',
  UPDATE_FIELDS = 'UPDATE_FIELDS',
  UPDATE_VALUES = 'UPDATE_VALUES',
  UPDATE_AREAS = 'UPDATE_AREAS',
  CLEAR = 'CLEAR',
  TELE_UPDATE_USERNAME = 'TELE_UPDATE_USERNAME',
}
export enum GetterType {
  FIELDS = 'FIELDS',
  CHECKBOX_FIELDS = 'CHECKBOX_FIELDS',
  VALUES = 'VALUES',
  CHECKBOX_VALUES = 'CHECKBOX_VALUES',
  CHECKBOX_DICT = 'CHECKBOX_DICT',
  INPUTS_DICT = 'INPUTS_DICT',
  AREAS = 'AREAS',
  AREA_OPTIONS = 'AREA_OPTIONS',
  INPUT_FIELDS = 'INPUT_FIELDS',
  INPUT_VALUES = 'INPUT_VALUES',
  NOTES = 'NOTES',
  TELE_USERNAME = 'TELE_USERNAME',
}
