export enum ActionType {
  FETCH_FIELDS = 'FETCH_FIELDS',
  FETCH_VALUES = 'FETCH_VALUES',
  FETCH_AREAS = 'FETCH_AREAS',
  SEND_VALUE = 'SEND_VALUE',
  CLEAR = 'CLEAR',
}
export enum MutationType {
  UPDATE_VALUE = 'UPDATE_VALUE',
  UPDATE_FIELDS = 'UPDATE_FIELDS',
  UPDATE_VALUES = 'UPDATE_VALUES',
  UPDATE_AREAS = 'UPDATE_AREAS',
  CLEAR = 'CLEAR',
}
export enum GetterType {
  FIELDS = 'FIELDS',
  CHECKBOX_FIELDS = 'CHECKBOX_FIELDS',
  VALUES = 'VALUES',
  CHECKBOX_VALUES = 'CHECKBOX_VALUES',
  AREAS = 'AREAS',
  AREA_OPTIONS = 'AREA_OPTIONS',
  INPUT_FIELDS = 'INPUT_FIELDS',
  INPUT_VALUES = 'INPUT_VALUES',
}
